### ISSUE TITLE
move users and questions.js to dataHandlers would make more sense no ?

### ISSUE THREAD

**Issue by Karyum** [WebAhead12/Who-Asked#12]
https://github.com/WebAhead12/Who-Asked/blob/main/database/questions.js
https://github.com/WebAhead12/Who-Asked/blob/main/database/users.js

shouldn't these move to dataHandlers? 

btw usually files that are an abstraction for the db queries (just like what you have) are usually stored in a folder called `models`, I'm not saying you need to do this here just a general fact.

**Comment by mohammadfaur** [comment]
thanks for letting us know, you're right, files have been adjusted.
